#!/usr/bin/env python3
"""Ninja Build File Generator for ndsDecomp.

Scans src/arm9 and src/arm7 for matched C/C++ source files (.c and .cpp) and
creates build.ninja rules that compile them with mwccarm. This is a basic
"does everything still compile" smoke test - actual byte-matching verification
is tools/match.py, run per-function (see CONTRIBUTING.md).
"""

import os

MWCCARM_PATH = os.path.join("tools", "mwccarm", "dsi", "1.3", "mwccarm.exe")
LICENSE_PATH = os.path.abspath(os.path.join("tools", "mwccarm", "license.dat"))

NINJA_HEADER = f"""# Generated by configure.py - Do not edit directly

ninja_required_version = 1.3

# Variables
mwccarm = {MWCCARM_PATH}
cflags_common = -O4,p -enum int -lang c++ -char signed -interworking -gccext,on -msgstyle gcc -Iinclude
cflags_arm9 = $cflags_common -proc arm946e
cflags_arm7 = $cflags_common -proc arm7tdmi

rule extract_pictochat
  command = python tools/extract_pictochat.py
  description = EXTRACT assets/pictochat.nds

rule extract_firmware
  command = python tools/extract_firmware.py
  description = EXTRACT assets/firmware.bin (firmware investigation - see notes/firmware-investigation.md)

rule cc_arm9
  command = cmd /c "set LM_LICENSE_FILE={LICENSE_PATH} && $mwccarm $cflags_arm9 -c $in -o $out"
  description = CC (ARM9) $in

rule cc_arm7
  command = cmd /c "set LM_LICENSE_FILE={LICENSE_PATH} && $mwccarm $cflags_arm7 -c $in -o $out"
  description = CC (ARM7) $in

# Build targets
build extracted/pictochat_arm9.bin extracted/pictochat_arm7.bin extracted/pictochat_arm9_dec.bin extracted/pictochat_arm7_dec.bin: extract_pictochat assets/pictochat.nds
build extracted/part1_arm9_boot.bin extracted/part2_arm7_boot.bin extracted/part3_raw.bin extracted/part4_raw.bin extracted/part5_raw.bin: extract_firmware assets/firmware.bin
"""


def scan_sources(src_dir):
    sources = []
    if not os.path.exists(src_dir):
        return sources
    for root, _, files in os.walk(src_dir):
        for f in files:
            if f.endswith(".c") or f.endswith(".cpp"):
                sources.append(os.path.join(root, f))
    return sources


def main():
    print("[+] Generating build.ninja...")

    arm9_sources = scan_sources(os.path.join("src", "arm9"))
    arm7_sources = scan_sources(os.path.join("src", "arm7"))

    ninja_body = [NINJA_HEADER]

    for src in arm9_sources:
        ext = ".cpp" if src.endswith(".cpp") else ".c"
        rel_obj = os.path.join("build", "arm9", os.path.basename(src).replace(ext, ".o"))
        ninja_body.append(f"build {rel_obj}: cc_arm9 {src}")

    for src in arm7_sources:
        ext = ".cpp" if src.endswith(".cpp") else ".c"
        rel_obj = os.path.join("build", "arm7", os.path.basename(src).replace(ext, ".o"))
        ninja_body.append(f"build {rel_obj}: cc_arm7 {src}")

    ninja_body.append("\ndefault extracted/pictochat_arm9_dec.bin extracted/pictochat_arm7_dec.bin\n")

    with open("build.ninja", "w") as f:
        f.write("\n".join(ninja_body))

    print(f"[+] build.ninja generated successfully ({len(arm9_sources)} ARM9 sources, {len(arm7_sources)} ARM7 sources)")


if __name__ == "__main__":
    main()
