//cpp
// decomp: module=unk_autoload_0 addr=0x023378ac name=FUN_023378ac

// Twin of FUN_02337818: the two disassemble to the same sequence of
// instructions, so this is that function's source with the constants and
// call targets remapped to this one's. Generated by tools/twin.py and
// verified byte-identical by tools/match.py - see notes/tooling.md.

#pragma thumb on
extern "C" {
extern void FUN_02337930(int, int, int, int, int);
void FUN_023378ac(int a, int b)
{
    FUN_02337930(0x20, a, b, 0, 0);
}
}
