//cpp
// decomp: module=unk_autoload_0 addr=0x02336900 name=FUN_02336900

// Twin of FUN_02336800: the two disassemble to the same sequence of
// instructions, so this is that function's source with the constants and
// call targets remapped to this one's. Generated by tools/twin.py and
// verified byte-identical by tools/match.py - see notes/tooling.md.

#pragma thumb on
extern "C" {
extern void FUN_02337240(int, int, int, unsigned int, int);
extern void FUN_02337454(int, int, unsigned int);
extern int G_0236a17c[];
void FUN_02336900(int a, int b, unsigned int n, int d)
{
    if (G_0236a17c[0] != -1 && n > 0x30) {
        FUN_02337240(G_0236a17c[0], a, b + 0x7000400, n, 1);
        return;
    }
    FUN_02337454(a, b + 0x7000400, n);
}
}
