//cpp
// decomp: module=unk_autoload_0 addr=0x02336ce8 name=FUN_02336ce8

// Twin of FUN_023369b8: the two disassemble to the same sequence of
// instructions, so this is that function's source with the constants and
// call targets remapped to this one's. Generated by tools/twin.py and
// verified byte-identical by tools/match.py - see notes/tooling.md.

#pragma thumb on
extern "C" {
extern void *FUN_02336764(void);
extern void FUN_02337240(int, int, int, unsigned int, int);
extern void FUN_02337454(int, int, unsigned int);
extern int G_0236a17c[];

void FUN_02336ce8(int a, int b, unsigned int n, int d)
{
    void *p = FUN_02336764();
    if (G_0236a17c[0] != -1 && n > 0x30) {
        FUN_02337240(G_0236a17c[0], a, (int)p + b, n, 1);
        return;
    }
    FUN_02337454(a, (int)p + b, n);
}
}
