//cpp
// decomp: module=unk_autoload_0 addr=0x02331798 name=FUN_02331798

// Twin of FUN_0233178c: the two disassemble to the same sequence of
// instructions, so this is that function's source with the constants and
// call targets remapped to this one's. Generated by tools/twin.py and
// verified byte-identical by tools/match.py - see notes/tooling.md.

#pragma thumb on
extern "C" {
void FUN_02331798(int i, int v)
{
    ((int *)0x2fffda0)[i] = v;
}
}
