//cpp
// decomp: module=unk_autoload_0 addr=0x0232fc34 name=FUN_0232fc34

// Twin of FUN_0232fc14: the two disassemble to the same sequence of
// instructions, so this is that function's source with the constants and
// call targets remapped to this one's. Generated by tools/twin.py and
// verified byte-identical by tools/match.py - see notes/tooling.md.

#pragma thumb on
extern "C" {
extern void FUN_0232fbd8(int, int, int, int);
extern void FUN_023378ac(int, int);
extern void FUN_02338074(int);
void FUN_0232fc34(int a, int b, int c, int d)
{
    FUN_0232fbd8(a, c, d, d);
    FUN_023378ac(a, a + b);
    FUN_02338074(a);
}
}
