//cpp
// decomp: module=unk_autoload_0 addr=0x02336880 name=FUN_02336880

// Twin of FUN_02336800: the two disassemble to the same sequence of
// instructions, so this is that function's source with the constants and
// call targets remapped to this one's. Generated by tools/twin.py and
// verified byte-identical by tools/match.py - see notes/tooling.md.

#pragma thumb on
extern "C" {
extern void FUN_023372b0(int, int, int, unsigned int, int);
extern void FUN_02337424(int, int, unsigned int);
extern int G_0236a17c[];
void FUN_02336880(int a, int b, unsigned int n, int d)
{
    if (G_0236a17c[0] != -1 && n > 0x1c) {
        FUN_023372b0(G_0236a17c[0], a, b + 0x5000600, n, 1);
        return;
    }
    FUN_02337424(a, b + 0x5000600, n);
}
}
