//cpp
// decomp: module=unk_autoload_0 addr=0x02327d68 name=FUN_02327d68

// Twin of FUN_02327d24: the two disassemble to the same sequence of
// instructions, so this is that function's source with the constants and
// call targets remapped to this one's. Generated by tools/twin.py and
// verified byte-identical by tools/match.py - see notes/tooling.md.

#pragma thumb on
extern "C" {
extern int FUN_023271c0(int, int);
extern void FUN_02320978(int);
extern int FUN_023212ec(void);
extern int FUN_023212f8(void);
extern int FUN_02321304(void);
extern int FUN_0232e004(int *, int, int);
extern int G_0233b4d8[];
void FUN_02327d68(void)
{
    if (FUN_023271c0(8, 1) != 1) { FUN_02320978(0xc); return; }
    if (FUN_023212ec() == 1) {
        int a = FUN_023212f8();
        int b = FUN_02321304();
        if (FUN_0232e004(G_0233b4d8, a, b) == 3) FUN_02320978(0xf);
    }
}
}
