//cpp
// decomp: module=unk_autoload_0 addr=0x023378e0 name=FUN_023378e0

// Twin of FUN_023376e0: the two disassemble to the same sequence of
// instructions, so this is that function's source with the constants and
// call targets remapped to this one's. Generated by tools/twin.py and
// verified byte-identical by tools/match.py - see notes/tooling.md.

#pragma thumb on
extern "C" {
extern void FUN_02337930(int, int, int, int, int);
void FUN_023378e0(int a, int b, int c, int d)
{
    FUN_02337930(6, a, b, c, d);
}
}
