// decomp: module=arm7 addr=0x022d37b0 name=FUN_022d37b0
// flags: -noThumb

// Twin of FUN_022d378c: the two disassemble to the same sequence of
// instructions, so this is that function's source with the constants and
// call targets remapped to this one's. Generated by tools/twin.py and
// verified byte-identical by tools/match.py - see notes/tooling.md.

extern unsigned short *FUN_037d14bc(void);
extern void FUN_037d1464(void);
void FUN_022d37b0(void)
{
    unsigned short *p = FUN_037d14bc();
    p[0] = 0x1b;
    p[1] = 4;
    FUN_037d1464();
}
