// decomp: module=arm7 addr=0x022d1ed8 name=FUN_022d1ed8
// flags: -noThumb

// Twin of FUN_022d14e4: the two disassemble to the same sequence of
// instructions, so this is that function's source with the constants and
// call targets remapped to this one's. Generated by tools/twin.py and
// verified byte-identical by tools/match.py - see notes/tooling.md.

extern unsigned short *FUN_037d14bc(void);
extern void FUN_037d1464(void);
void FUN_022d1ed8(unsigned short a, unsigned short b)
{
    unsigned short *p = FUN_037d14bc();
    p[0] = 11;
    p[1] = 1;
    p[2] = a;
    p[3] = b;
    FUN_037d1464();
}
